### ISSUE TITLE
KADEMCS-US-006 | My School

### ISSUE THREAD

**Issue by pamelagbl** [cobuildlab/kadem-web#12]
**ID:** US-KADEM06

**User Story**

As a teacher I want to be able to see the detail of my schools drivers in a read only format with my current temperature as an overlay.

**Criteria of Acceptance**
As a teacher I want to click the my School menu at the bottom of the screen and be brought to the My School detail view.

1. The My School Detail view will show a vertical bar graph that shows the schools temperature for each driver on a scale of 1-5
2. The bars for each driver will be color coded as follows:
     - Red (Initial value) Scale 1- 1.67
     - Yellow (grade point average) Scale 1.68 – 3.33
     - Green (Current value) Scale 3.34 – 5.0
3. I point on each bar graph will indicate where the teacher who is logged ins current temperature sits.  The dots will be connected by a dotted line overlay.
4. User can click the HOME icon to get back to the main landing page.

**Comment by alacret** [comment]
Blue bars are MyVoice, yellow line is MySchool (no word assessment)

**Comment by alacret** [comment]
Mouse over of bar says ‘My Assessment’: Change mouse over to say ‘MyVoice’
