### ISSUE TITLE
activate REMEMBER ME option for the Login

### ISSUE THREAD

**Issue by alacret** [cobuildlab/kadem-web#27]
Use firebase session persistence Feature

**Comment by alacret** [comment]
Remember ME option should keep the user log in until manual Log out

**Comment by pamelagbl** [comment]
@Lurazer Colocar delmismo tamaño el texto Remember me como Forgot Password
![Screenshot_2](https://user-images.githubusercontent.com/38106497/56084718-1a43a900-5e05-11e9-84da-6f12948f659e.png)

**Comment by pamelagbl** [comment]
listo esto? @Lurazer listo esto?
