### ISSUE TITLE
KADEMCS-RE-003 | Place a "loading" indicator in each process of waiting or loading the page

### ISSUE THREAD

**Issue by pamelagbl** [cobuildlab/kadem-web#30]
In the following processes place loading:

- Login: When the user has pressed the login button, they should see the loading.
- Recover Password: When the user has requested the recover password, the load indicator should be displayed.
- Home
- My Voice 
- Edit indicators
- Profile
- Edit profile
- My School

**Comment by pamelagbl** [comment]
When an update of the drivers (MyVoice) is performed, the process for the user is unknown until the Drivers update message appears, it is required to place a load loading indicator so that the user waits and knows that a process is happening. @CesarDav 

![image](https://user-images.githubusercontent.com/38106497/56060411-c2d60800-5d34-11e9-9793-1c854b8906b4.png)

**Comment by pamelagbl** [comment]
Center the loading when entering my school @CesarDav 
![image](https://user-images.githubusercontent.com/38106497/56060572-40017d00-5d35-11e9-8a73-ee97eef1caf4.png)

**Comment by CesarDav** [comment]
@pamelagbl  
I solved my school's spinner problem but I still have to solve my voice
