### ISSUE TITLE
Messages Boxes

### ISSUE THREAD

**Issue by alacret** [cobuildlab/kadem-web#36]
Create a collection of messages with a field of message, date and schoolId.

The Last message should be presented to the User in the HomeView

**Comment by pamelagbl** [comment]
@alacret Some examples for this collection of messages?

**Comment by alacret** [comment]
@pamelagbl 
The Message is gonna be pulled from the database.

Is a Message per District.

So, in the admin interface, a DIstrict could have a Message that shall be displayed on all the Schools of that District.

Structure:
A School belongs to a Region, 
A Region belongs to a District,

**Comment by pamelagbl** [comment]
ok this message will we show in this view? @alacret And so you say this will be from the firebase administrator?
![image](https://user-images.githubusercontent.com/38106497/56164345-81489580-5f9e-11e9-8164-451a9759731e.png)

**Comment by alacret** [comment]
@pamelagbl yes
