### ISSUE TITLE
Liker scale layout

### ISSUE THREAD

**Issue by alacret** [cobuildlab/kadem-web#38]
Radio buttons 1 – 5 have numbers only: Put above each radio button in small light font (1 -5) Strongly Disagree, Disagree, Neutral, Agree, Strongly Agree

**Comment by pamelagbl** [comment]
![image](https://user-images.githubusercontent.com/38106497/56161976-e7321e80-5f98-11e9-8329-978679f1ac95.png)

**Comment by pamelagbl** [comment]
@alacret This is necessary for the soonest possible, correct?

**Comment by alacret** [comment]
yes @pamelagbl

**Comment by pamelagbl** [comment]
@CesarDav 
you must also place it in Initial-evaluation using the credentials:
email: pam.britoleal@gmail.com
pass: p.123456
![image](https://user-images.githubusercontent.com/38106497/56393607-f61c0980-6202-11e9-9ab3-1acb0c107a59.png)
