### ISSUE TITLE
Sense of Belonging Driver

### ISSUE THREAD

**Issue by alacret** [cobuildlab/kadem-web#39]
Sense of Belonging Driver.  Indicators 4 and 5 are connected and when one is changed the other changes at same time
Each indicator operates independently

**Comment by pamelagbl** [comment]
@alacret You mean these indicators?
![image](https://user-images.githubusercontent.com/38106497/56162783-cbc81300-5f9a-11e9-8516-d8907af7374e.png)

**Comment by alacret** [comment]
@pamelagbl already DONE
