### ISSUE TITLE
Kadem | Within MyProfile page please delete ‘Initial Assessment’

### ISSUE THREAD

**Issue by pamelagbl** [cobuildlab/kadem-web#70]
![image](https://user-images.githubusercontent.com/38106497/57319570-db82d500-70ca-11e9-90f8-2e5aa26e7b9a.png)

**Comment by alacret** [comment]
Either we removed or changed?

**Comment by CesarDav** [comment]
@alacret  Could you give more specifications?

**Comment by alacret** [comment]
@CesarDav this is already done
